version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: club-postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./club-backend
    container_name: club-backend
    restart: unless-stopped
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_DOCKER_PORT}
      PORT: ${NODE_DOCKER_PORT}

volumes:
  postgres_data:
